#ifndef TABLICA_CONSTANTS_H
#define TABLICA_CONSTANTS_H

#define DEFAULT_SERVER_PORT 60023
#define SERVER_MAXIMUM_CLIENTS 64
#define SERVER_BUFFER_SIZE 8192

#define DISPLAY_MAX_LINES 12
#define DISPLAY_PADDING 8
#define DISPLAY_MAX_FONTS 3

#endif //TABLICA_CONSTANTS_H
