plugins {
    id 'com.android.application'
}

apply from: "../version.gradle"

android {
    namespace "pl.zupanet.tablica"
    compileSdk 35

    defaultConfig {
        applicationId "pl.zupanet.tablica"
        minSdk 21
        targetSdk 35
        versionCode APP_VERSION_CODE
        versionName APP_VERSION_STRING
		
		ndk {
			abiFilters "armeabi-v7a", "arm64-v8a", "x86_64"
		}
		
		externalNativeBuild {
			cmake {
				arguments "-DANDROID_STL=c++_shared"
			}
		}

    }
	
	externalNativeBuild {
		cmake {
			path "../../CMakeLists.txt"
		}
	}

    signingConfigs {
        release {
            def store = System.getenv("ANDROID_KEYSTORE")
            if(store != null) {
                storeFile file(store)
                storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
                keyAlias System.getenv("ANDROID_KEY_ALIAS")
                keyPassword System.getenv("ANDROID_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        debug {
            debuggable true
            jniDebuggable true

            minifyEnabled false
            shrinkResources false
        }

        release {
            debuggable false

            signingConfig signingConfigs.release

            shrinkResources true
            minifyEnabled true

            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            ndk {
                debugSymbolLevel 'NONE'
            }
			
			if(store == null) {
				throw new GradleException("Missing ANDROID_KEYSTORE for release build")
			}
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

	sourceSets {
        main {
			assets.srcDirs += ["../../resources/common"]
        }
    }

    applicationVariants.configureEach { variant ->
		variant.outputs.configureEach { output ->

			def abi = output.getFilter(
				com.android.build.OutputFile.ABI
			)

			if (abi == null) {
				abi = "universal"
			}

			output.outputFileName =
				"TablicaZnakowa-" +
				variant.versionName +
				"-" +
				abi +
				"-" +
				variant.buildType.name +
				".apk"
		}
	}
}